version: "3"


services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=admin
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ../db_data/psql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  fastparser:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    depends_on:
      - postgres
    ports:
    - "8000:8000"
    links:
      - postgres:postgres
    restart: always